export const UNIT_KERJA_OPTIONS = [
  'Pemerintahan Daerah',
  'Sekretariat Daerah',
  'Bagian Tata Pemerintahan & Kerjasama',
  'Bagian Kesejahteraan Rakyat',
  'Bagian Hukum',
  'Bagian Perekonomian & Sumber Daya Alam',
  'Bagian Administrasi Pembangunan',
  'Bagian Pengadaian Barang & Jasa',
  'Bagian Umum',
  'Bagian Organisasi',
  'Bagian Protokol Komunikasi & Pimpinan',
  'Bagian Perencanaan & Keuangan',
  'Badan Kepegawaian dan Pengembangan Sumber Daya Manusia',
  'Badan Kesatuan Bangsa dan Politik',
  'Badan Penanggulangan Bencana Daerah',
  'Badan Pendapatan Daerah',
  'Badan Penelitian dan Pengembangan Daerah',
  'Badan Pengelolaan Keuangan dan Aset Daerah',
  'Badan Perencanaan Pembangunan Daerah',
  'Dinas Kependudukan dan Pencatatan Sipil',
  'Dinas Kesehatan',
  'Dinas Komunikasi Informatika Statistik dan Persandian',
  'Dinas Lingkungan Hidup',
  'Dinas Pekerjaan Umum dan Penataan Ruang',
  'Dinas Pemadam Kebakaran dan Penyelamatan',
  'Dinas Pemberdayaan Masyarakat dan Desa',
  'Dinas Pemberdayaan Perempuan dan Perlindungan Anak serta Pengendalian Penduduk dan Keluarga Berencana',
  'Dinas Pemuda, Olahraga dan Pariwisata',
  'Dinas Penanaman Modal dan Perizinan Terpadu Satu Pintu',
  'Dinas Pendidikan dan Kebudayaan',
  'Dinas Perhubungan',
  'Dinas Perikanan dan Peternakan',
  'Dinas Perindustrian, Perdagangan Koperasi dan Usaha Kecil Menengah',
  'Dinas Perpustakaan dan Kearsipan',
  'Dinas Pertanian dan Ketahanan Pangan',
  'Dinas Perumahan Rakyat dan Kawasan Permukiman serta Pertahanan',
  'Dinas Sosial',
  'Dinas Transmigrasi dan Tenaga Kerja',
  'Inspektorat Daerah',
  'Satuan Polisi Pamong Praja',
  
  'Sekretariat DPRD',
];

export const ROLE_OPTIONS: { [key: string]: string } = {
    pelapor: 'pelapor',
    subbag_umum: 'Sub Bagian Umum',
    kabbag_umum: 'Kepala Bagian Umum',
    bupati: 'Bupati',
    wakil_bupati: 'Wakil Bupati',
    sekda: 'Sekretariat Daerah',
    as_i: 'Asisten I',
    as_ii: 'Asisten II',
    as_iii: 'Asisten III',
    staf_ahli: 'Staf Ahli',
    kabbag: 'Kepala Bagian',
};